# Header

menu:
  主页: /
  所有文章: /allPages
  随笔: /tags
  相册: /photos

# SubNav
subnav:
  github: "https://github.com/miko486/"
  weibo: "#"
  rss: /atom.xml
  zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
